version: "3.9"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smartagri
      MYSQL_USER: smart
      MYSQL_PASSWORD: smartpass
    ports: ["3306:3306"]
    volumes: [mysql_data:/var/lib/mysql]
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883","8883:8883"]
    volumes:
      - ./security/pki:/mosq/pki:ro
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on: [mysql, mosquitto]
    ports: ["8000:8000"]
    volumes:
      - ./security/pki:/app/pki:ro
  dashboard:
    build: ./dashboard
    ports: ["5173:5173"]
    depends_on: [backend]
volumes:
  mysql_data:
  
  